import { Component } from "@angular/core";
import { Dialog } from "../dialog.component";
import { position } from "../../utils/position";

/**
 * Extend the `Dialog` component to create an overflow menu.
 *
 * Not used directly. See overflow-menu.component and overflow-menu.directive for more
 */
@Component({
	selector: "ibm-overflow-menu-pane",
	template: `
		<ul
			#dialog
			class="bx--overflow-menu-options bx--overflow-menu-options--open"
			tabindex="-1">
			<ng-template
				[ngTemplateOutlet]="dialogConfig.content"
				[ngTemplateOutletContext]="{overflowMenu: this}">
			</ng-template>
		</ul>
	`
})
export class OverflowMenuPane extends Dialog {
	onDialogInit() {
		/**
		 *  -20 shifts the menu up to compensate for the
		 *  extra offset generated by the wrapper component.
		 *
		 *  60 shifts the menu right to align the arrow.
		 * (position service trys it's best to center everything,
		 * so we need to add some compensation)
		 */
		this.addGap["bottom"] = pos => position.addOffset(pos, -20, 60);
	}
}
